// src/components/graph/ClusterGroup.tsx
/**
 * Renders a single cluster with its card, edges, and nodes
 * Extracted from GraphVisualization for better modularity
 */

import { useMemo, useState } from 'react';
import type { GraphEdge, GraphNode as GraphNodeType } from '../../data/mockGraphData';
import type { ViewMode } from '../../types/app';
import type { Cluster } from '../../types/cluster';
import type { ClusterPosition, NodePosition } from '../../types/simulation';
import { ClusterCard } from './ClusterCard';
import { GraphEdges } from './GraphEdges';
import { GraphNode } from './GraphNode';
import { getConnectedNodes, getNodeSize, getNodeTypeColor } from './graphUtils';

interface ClusterGroupProps {
  cluster: Cluster;
  clusterPosition: ClusterPosition;
  nodes: GraphNodeType[];
  edges: GraphEdge[];
  finalNodePositions: Map<string, NodePosition>;
  selectedNode: GraphNodeType | null;
  hoveredNode: string | null;
  hoveredClusterId?: string | null;
  searchQuery: string;
  zoom: number;
  onNodeMouseEnter: (nodeId: string) => void;
  onNodeMouseLeave: () => void;
  onClusterMouseEnter: () => void;
  onClusterMouseLeave: () => void;
  onNodeMouseDown: (nodeId: string, e: React.MouseEvent) => void;
  onNodeClick: (node: GraphNodeType, e: React.MouseEvent) => void;
  onClusterClick: () => void;
  viewMode?: ViewMode;
  transitiveDeps?: {
    nodes: Set<string>;
    edges: Set<string>;
    edgeDepths: Map<string, number>;
    maxDepth: number;
  };
  transitiveDependents?: {
    nodes: Set<string>;
    edges: Set<string>;
    edgeDepths: Map<string, number>;
    maxDepth: number;
  };
  isSelected?: boolean;
  previewFilter?: {
    type: 'nodeType' | 'platform' | 'origin' | 'project' | 'package' | 'cluster';
    value: string;
  } | null;
}

export function ClusterGroup({
  cluster,
  clusterPosition,
  nodes,
  edges,
  finalNodePositions,
  selectedNode,
  hoveredNode,
  hoveredClusterId,
  searchQuery,
  zoom,
  onNodeMouseEnter,
  onNodeMouseLeave,
  onClusterMouseEnter,
  onClusterMouseLeave,
  onNodeMouseDown,
  onNodeClick,
  onClusterClick,
  viewMode = 'full',
  transitiveDeps,
  transitiveDependents,
  isSelected = false,
  previewFilter,
}: ClusterGroupProps) {
  const [isClusterHovered, setIsClusterHovered] = useState(false);

  const connectedNodes = useMemo(
    () => (selectedNode ? getConnectedNodes(selectedNode.id, edges) : new Set()),
    [selectedNode, edges],
  );

  const clusterNodes = cluster.nodes;

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      onClusterClick();
    }
  };

  return (
    <g
      role="button"
      aria-label={`${cluster.name} cluster, ${cluster.nodes.length} targets`}
      tabIndex={0}
      onMouseEnter={() => {
        setIsClusterHovered(true);
        onClusterMouseEnter();
      }}
      onMouseLeave={() => {
        setIsClusterHovered(false);
        onClusterMouseLeave();
      }}
      onKeyDown={handleKeyDown}
    >
      {/* Cluster card background */}
      <ClusterCard
        cluster={cluster}
        x={clusterPosition.x - clusterPosition.width / 2}
        y={clusterPosition.y - clusterPosition.height / 2}
        width={clusterPosition.width}
        height={clusterPosition.height}
        isHighlighted={isClusterHovered}
        isSelected={isSelected}
        zoom={zoom}
        onClick={onClusterClick}
      />

      {/* Internal edges */}
      <g className="internal-edges">
        <GraphEdges
          edges={edges}
          nodes={nodes}
          finalNodePositions={finalNodePositions}
          clusterPositions={new Map([[cluster.id, clusterPosition]])}
          selectedNode={selectedNode}
          hoveredNode={hoveredNode}
          clusterId={cluster.id}
          hoveredClusterId={hoveredClusterId}
          viewMode={viewMode}
          transitiveDeps={transitiveDeps}
          transitiveDependents={transitiveDependents}
          zoom={zoom}
        />
      </g>

      {/* Nodes */}
      <g className="nodes">
        {clusterNodes.map((node) => {
          const pos = finalNodePositions.get(node.id);
          if (!pos) return null;

          const isSelectedNode = selectedNode?.id === node.id;
          const isHovered = hoveredNode === node.id;
          const isConnected = selectedNode && connectedNodes.has(node.id);
          const isSearchMatch =
            searchQuery && node.name.toLowerCase().includes(searchQuery.toLowerCase());

          // Check if node matches the preview filter
          const matchesPreview =
            !previewFilter ||
            (previewFilter.type === 'nodeType' && node.type === previewFilter.value) ||
            (previewFilter.type === 'platform' && node.platform === previewFilter.value) ||
            (previewFilter.type === 'origin' && node.origin === previewFilter.value) ||
            (previewFilter.type === 'project' && node.project === previewFilter.value) ||
            (previewFilter.type === 'package' &&
              node.type === 'package' &&
              node.name === previewFilter.value);

          const isDimmed =
            (searchQuery && !isSearchMatch) ||
            (selectedNode && !isSelectedNode && !isConnected) ||
            (previewFilter && !matchesPreview);

          const size = getNodeSize(node, edges);
          const color = getNodeTypeColor(node.type);

          const x = clusterPosition.x + pos.x;
          const y = clusterPosition.y + pos.y;

          return (
            <GraphNode
              key={node.id}
              node={node}
              x={x}
              y={y}
              size={size}
              color={color}
              isSelected={isSelectedNode}
              isHovered={isHovered}
              isDimmed={isDimmed}
              zoom={zoom}
              onMouseEnter={() => onNodeMouseEnter(node.id)}
              onMouseLeave={onNodeMouseLeave}
              onMouseDown={(e) => onNodeMouseDown(node.id, e)}
              onClick={(e) => onNodeClick(node, e)}
            />
          );
        })}
      </g>
    </g>
  );
}

// src/components-lit/graph/cluster-group.ts
/**
 * ClusterGroup Lit Component
 *
 * Renders a cluster with its card background, internal edges, and nodes.
 * Orchestrates ClusterCard, GraphEdges, and GraphNode components.
 *
 * @example
 * ```html
 * <svg>
 *   <graph-cluster-group
 *     .cluster=${clusterData}
 *     .clusterPosition=${position}
 *     .nodes=${nodesArray}
 *     .edges=${edgesArray}
 *     .finalNodePositions=${positionsMap}
 *     zoom="1.0"
 *   ></graph-cluster-group>
 * </svg>
 * ```
 *
 * @fires node-mouseenter, node-mouseleave, node-mousedown, node-click
 * @fires cluster-mouseenter, cluster-mouseleave, cluster-click
 */

import { LitElement, html } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import type { GraphEdge, GraphNode as GraphNodeType } from '@/data/mockGraphData';
import type { ViewMode } from '@/types/app';
import type { Cluster } from '@/types/cluster';
import type { ClusterPosition, NodePosition } from '@/types/simulation';
import { getConnectedNodes, getNodeSize, getNodeTypeColor } from '@/components/graph/graphUtils';
import './cluster-card';
import './graph-edges';
import './graph-node';

@customElement('graph-cluster-group')
export class GraphClusterGroup extends LitElement {
  // No Shadow DOM for SVG
  protected createRenderRoot() {
    return this;
  }

  // ========================================
  // Properties
  // ========================================

  @property({ attribute: false })
  declare cluster: Cluster;

  @property({ attribute: false })
  declare clusterPosition: ClusterPosition;

  @property({ attribute: false })
  declare nodes: GraphNodeType[];

  @property({ attribute: false })
  declare edges: GraphEdge[];

  @property({ attribute: false })
  declare finalNodePositions: Map<string, NodePosition>;

  @property({ attribute: false })
  declare selectedNode: GraphNodeType | null;

  @property({ attribute: false })
  declare hoveredNode: string | null;

  @property({ attribute: false })
  declare hoveredClusterId: string | null;

  @property({ type: String, attribute: 'search-query' })
  searchQuery: string = '';

  @property({ type: Number })
  zoom: number = 1.0;

  @property({ type: String, attribute: 'view-mode' })
  viewMode: ViewMode = 'full';

  @property({ attribute: false })
  declare transitiveDeps: any;

  @property({ attribute: false })
  declare transitiveDependents: any;

  @property({ type: Boolean, attribute: 'is-selected' })
  isSelected: boolean = false;

  @property({ attribute: false })
  declare previewFilter: any;

  @state()
  private declare isClusterHovered: boolean;

  // ========================================
  // Event Handlers
  // ========================================

  private handleClusterMouseEnter() {
    this.isClusterHovered = true;
    this.dispatchEvent(new CustomEvent('cluster-mouseenter', { bubbles: true, composed: true }));
  }

  private handleClusterMouseLeave() {
    this.isClusterHovered = false;
    this.dispatchEvent(new CustomEvent('cluster-mouseleave', { bubbles: true, composed: true }));
  }

  private handleClusterClick() {
    this.dispatchEvent(new CustomEvent('cluster-click', { bubbles: true, composed: true }));
  }

  private handleClusterKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      this.handleClusterClick();
    }
  }

  // ========================================
  // Helpers
  // ========================================

  private get connectedNodes(): Set<string> {
    return this.selectedNode ? getConnectedNodes(this.selectedNode.id, this.edges) : new Set();
  }

  private get clusterNodes(): GraphNodeType[] {
    return this.cluster?.nodes || [];
  }

  // ========================================
  // Render
  // ========================================

  render() {
    if (!this.cluster || !this.clusterPosition) return html``;

    const clusterPositionsMap = new Map([[this.cluster.id, this.clusterPosition]]);

    return html`
      <g
        role="button"
        aria-label="${this.cluster.name} cluster, ${this.cluster.nodes.length} targets"
        tabindex="0"
        @mouseenter=${this.handleClusterMouseEnter}
        @mouseleave=${this.handleClusterMouseLeave}
        @keydown=${this.handleClusterKeyDown}
      >
        <!-- Cluster card background -->
        <graph-cluster-card
          .cluster=${this.cluster}
          .x=${this.clusterPosition.x - this.clusterPosition.width / 2}
          .y=${this.clusterPosition.y - this.clusterPosition.height / 2}
          .width=${this.clusterPosition.width}
          .height=${this.clusterPosition.height}
          .isHighlighted=${this.isClusterHovered}
          .isSelected=${this.isSelected}
          .zoom=${this.zoom}
          .clickable=${true}
          @cluster-click=${this.handleClusterClick}
        ></graph-cluster-card>

        <!-- Internal edges -->
        <g class="internal-edges">
          <graph-edges
            .edges=${this.edges}
            .nodes=${this.nodes}
            .finalNodePositions=${this.finalNodePositions}
            .clusterPositions=${clusterPositionsMap}
            .selectedNode=${this.selectedNode}
            .hoveredNode=${this.hoveredNode}
            cluster-id=${this.cluster.id}
            .hoveredClusterId=${this.hoveredClusterId}
            view-mode=${this.viewMode}
            .transitiveDeps=${this.transitiveDeps}
            .transitiveDependents=${this.transitiveDependents}
            .zoom=${this.zoom}
          ></graph-edges>
        </g>

        <!-- Nodes -->
        <g class="nodes">
          ${this.clusterNodes.map((node) => {
            const pos = this.finalNodePositions.get(node.id);
            if (!pos) return null;

            const isSelectedNode = this.selectedNode?.id === node.id;
            const isHovered = this.hoveredNode === node.id;
            const isConnected = this.selectedNode && this.connectedNodes.has(node.id);
            const isSearchMatch =
              this.searchQuery && node.name.toLowerCase().includes(this.searchQuery.toLowerCase());

            const matchesPreview =
              !this.previewFilter ||
              (this.previewFilter.type === 'nodeType' && node.type === this.previewFilter.value) ||
              (this.previewFilter.type === 'platform' && node.platform === this.previewFilter.value) ||
              (this.previewFilter.type === 'origin' && node.origin === this.previewFilter.value) ||
              (this.previewFilter.type === 'project' && node.project === this.previewFilter.value) ||
              (this.previewFilter.type === 'package' &&
                node.type === 'package' &&
                node.name === this.previewFilter.value);

            const isDimmed =
              (this.searchQuery && !isSearchMatch) ||
              (this.selectedNode && !isSelectedNode && !isConnected) ||
              (this.previewFilter && !matchesPreview);

            const size = getNodeSize(node, this.edges);
            const color = getNodeTypeColor(node.type);
            const x = this.clusterPosition.x + pos.x;
            const y = this.clusterPosition.y + pos.y;

            return html`
              <graph-node
                .node=${node}
                .x=${x}
                .y=${y}
                .size=${size}
                .color=${color}
                .isSelected=${isSelectedNode}
                .isHovered=${isHovered}
                .isDimmed=${isDimmed}
                .zoom=${this.zoom}
                @node-mouseenter=${() =>
                  this.dispatchEvent(
                    new CustomEvent('node-mouseenter', {
                      detail: { nodeId: node.id },
                      bubbles: true,
                      composed: true,
                    })
                  )}
                @node-mouseleave=${() =>
                  this.dispatchEvent(new CustomEvent('node-mouseleave', { bubbles: true, composed: true }))}
                @node-mousedown=${(e: CustomEvent) =>
                  this.dispatchEvent(
                    new CustomEvent('node-mousedown', {
                      detail: { nodeId: node.id, originalEvent: e.detail.originalEvent },
                      bubbles: true,
                      composed: true,
                    })
                  )}
                @node-click=${(e: CustomEvent) =>
                  this.dispatchEvent(
                    new CustomEvent('node-click', {
                      detail: { node, originalEvent: e.detail.originalEvent },
                      bubbles: true,
                      composed: true,
                    })
                  )}
              ></graph-node>
            `;
          })}
        </g>
      </g>
    `;
  }
}

// Export for TypeScript type checking
declare global {
  interface HTMLElementTagNameMap {
    'graph-cluster-group': GraphClusterGroup;
  }
}
