// src/components/graph/GraphCluster.tsx
import type { ReactNode } from 'react';

interface GraphClusterProps {
  clusterId: string;
  x: number;
  y: number;
  width: number;
  height: number;
  color: string;
  nodeCount: number;
  origin: 'local' | 'external';
  isHovered: boolean;
  onMouseEnter: () => void;
  onMouseLeave: () => void;
  children: ReactNode;
}

export function GraphCluster({
  clusterId,
  x,
  y,
  width,
  height,
  color,
  nodeCount,
  origin,
  isHovered,
  onMouseEnter,
  onMouseLeave,
  children,
}: GraphClusterProps) {
  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      onMouseEnter();
    }
  };

  return (
    <g
      role="group"
      aria-label={`${clusterId} cluster, ${nodeCount} targets, ${origin === 'external' ? 'external' : 'local'}`}
      tabIndex={0}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      onKeyDown={handleKeyDown}
      style={{ transition: 'all 0.3s ease' }}
    >
      {/* Hover glow with smooth transition */}
      {isHovered && (
        <rect
          x={x - width / 2 - 3}
          y={y - height / 2 - 3}
          width={width + 6}
          height={height + 6}
          fill="none"
          stroke={color}
          strokeWidth={3}
          rx={14}
          opacity={0.6}
          filter="url(#glow-strong)"
          style={{ transition: 'opacity 0.3s ease, stroke-width 0.3s ease' }}
        />
      )}

      {/* Cluster background with subtle gradient */}
      <defs>
        <radialGradient id={`cluster-bg-${clusterId}`} cx="50%" cy="50%" r="70%">
          <stop offset="0%" stopColor={color} stopOpacity={0.08} />
          <stop offset="100%" stopColor={color} stopOpacity={0.03} />
        </radialGradient>
        <linearGradient id={`cluster-inner-shadow-${clusterId}`} x1="0%" y1="0%" x2="0%" y2="100%">
          <stop offset="0%" stopColor="rgba(0, 0, 0, 0.2)" />
          <stop offset="50%" stopColor="rgba(0, 0, 0, 0)" />
          <stop offset="100%" stopColor="rgba(0, 0, 0, 0.1)" />
        </linearGradient>
      </defs>

      {/* Background with gradient */}
      <rect
        x={x - width / 2}
        y={y - height / 2}
        width={width}
        height={height}
        fill={`url(#cluster-bg-${clusterId})`}
        stroke="none"
        rx={12}
        opacity={isHovered ? 0.9 : 0.7}
        style={{ transition: 'opacity 0.3s ease' }}
      />

      {/* Inner shadow for depth */}
      <rect
        x={x - width / 2}
        y={y - height / 2}
        width={width}
        height={height}
        fill={`url(#cluster-inner-shadow-${clusterId})`}
        stroke="none"
        rx={12}
        opacity={0.3}
        pointerEvents="none"
      />

      {/* Cluster border - softer and more subtle */}
      <rect
        x={x - width / 2}
        y={y - height / 2}
        width={width}
        height={height}
        fill="none"
        stroke={color}
        strokeWidth={isHovered ? 2.5 : 2}
        strokeDasharray="6,6"
        rx={12}
        opacity={isHovered ? 0.85 : 0.5}
        style={{ transition: 'all 0.3s ease' }}
      />

      {/* Cluster label */}
      <text
        x={x}
        y={y - height / 2 - 8}
        fill={color}
        textAnchor="middle"
        style={{
          fontFamily: 'DM Sans, sans-serif',
          fontSize: '14px',
          fontWeight: 'var(--font-weight-medium)',
          filter: isHovered ? 'url(#glow)' : 'none',
          transition: 'filter 0.3s ease',
        }}
      >
        {clusterId}
      </text>
      <text
        x={x}
        y={y - height / 2 + 7}
        fill={color}
        textAnchor="middle"
        opacity={isHovered ? 0.8 : 0.5}
        style={{
          fontFamily: 'Inter, sans-serif',
          fontSize: '10px',
          transition: 'opacity 0.3s ease',
        }}
      >
        {origin === 'external' ? 'EXTERNAL' : 'LOCAL'} · {nodeCount} targets
      </text>

      {/* Content (edges and nodes) */}
      {children}
    </g>
  );
}

// src/components-lit/graph/graph-cluster.ts
/**
 * GraphCluster Lit Component
 *
 * SVG cluster container with background, border, and glow effects.
 * Renders as a rounded rectangle with label, target count, and children.
 *
 * @example
 * ```html
 * <svg>
 *   <graph-cluster
 *     cluster-id="MyProject"
 *     x="100"
 *     y="100"
 *     width="200"
 *     height="150"
 *     color="#8B5CF6"
 *     node-count="5"
 *     origin="local"
 *   >
 *     <!-- child nodes and edges -->
 *   </graph-cluster>
 * </svg>
 * ```
 *
 * @fires cluster-mouseenter - Dispatched on mouse enter
 * @fires cluster-mouseleave - Dispatched on mouse leave
 * @fires cluster-click - Dispatched on click
 */

import { LitElement, svg } from 'lit';

export class GraphCluster extends LitElement {
  static properties = {
    clusterId: { type: String, attribute: 'cluster-id' },
    x: { type: Number },
    y: { type: Number },
    width: { type: Number },
    height: { type: Number },
    color: { type: String },
    nodeCount: { type: Number, attribute: 'node-count' },
    origin: { type: String },
    isHovered: { type: Boolean, attribute: 'is-hovered' },
  };

  // No Shadow DOM for SVG elements
  protected override createRenderRoot() {
    return this;
  }

  // ========================================
  // Properties
  // ========================================

  declare clusterId: string | undefined;
  declare x: number | undefined;
  declare y: number | undefined;
  declare width: number | undefined;
  declare height: number | undefined;
  declare color: string | undefined;
  declare nodeCount: number | undefined;
  declare origin: 'local' | 'external' | undefined;
  declare isHovered: boolean | undefined;

  // ========================================
  // Event Handlers
  // ========================================

  private handleMouseEnter() {
    this.dispatchEvent(
      new CustomEvent('cluster-mouseenter', {
        bubbles: true,
        composed: true,
      })
    );
  }

  private handleMouseLeave() {
    this.dispatchEvent(
      new CustomEvent('cluster-mouseleave', {
        bubbles: true,
        composed: true,
      })
    );
  }

  private handleClick() {
    this.dispatchEvent(
      new CustomEvent('cluster-click', {
        bubbles: true,
        composed: true,
      })
    );
  }

  private handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      this.handleClick();
    }
  }

  // ========================================
  // Render
  // ========================================

  override render() {
    const clusterId = this.clusterId ?? '';
    const x = this.x ?? 0;
    const y = this.y ?? 0;
    const width = this.width ?? 0;
    const height = this.height ?? 0;
    const color = this.color ?? '#888';
    const nodeCount = this.nodeCount ?? 0;
    const origin = this.origin ?? 'local';
    const isHovered = this.isHovered ?? false;

    // Unique IDs for gradients
    const bgGradientId = `cluster-bg-${clusterId}`;
    const innerShadowId = `cluster-inner-shadow-${clusterId}`;

    return svg`
      <g
        role="group"
        aria-label="${clusterId} cluster, ${nodeCount} targets, ${origin === 'external' ? 'external' : 'local'}"
        tabindex="0"
        @mouseenter=${this.handleMouseEnter}
        @mouseleave=${this.handleMouseLeave}
        @click=${this.handleClick}
        @keydown=${this.handleKeyDown}
        style="transition: all 0.3s ease; cursor: pointer"
      >
        <!-- Hover glow with smooth transition -->
        ${isHovered
          ? svg`
              <rect
                x="${x - width / 2 - 3}"
                y="${y - height / 2 - 3}"
                width="${width + 6}"
                height="${height + 6}"
                fill="none"
                stroke="${color}"
                stroke-width="3"
                rx="14"
                opacity="0.6"
                filter="url(#glow-strong)"
                style="transition: opacity 0.3s ease, stroke-width 0.3s ease"
              />
            `
          : ''}

        <!-- Gradient definitions -->
        <defs>
          <radialGradient id="${bgGradientId}" cx="50%" cy="50%" r="70%">
            <stop offset="0%" stop-color="${color}" stop-opacity="0.08" />
            <stop offset="100%" stop-color="${color}" stop-opacity="0.03" />
          </radialGradient>
          <linearGradient id="${innerShadowId}" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" stop-color="rgba(0, 0, 0, 0.2)" />
            <stop offset="50%" stop-color="rgba(0, 0, 0, 0)" />
            <stop offset="100%" stop-color="rgba(0, 0, 0, 0.1)" />
          </linearGradient>
        </defs>

        <!-- Background with gradient -->
        <rect
          x="${x - width / 2}"
          y="${y - height / 2}"
          width="${width}"
          height="${height}"
          fill="url(#${bgGradientId})"
          stroke="none"
          rx="12"
          opacity="${isHovered ? 0.9 : 0.7}"
          style="transition: opacity 0.3s ease"
        />

        <!-- Inner shadow for depth -->
        <rect
          x="${x - width / 2}"
          y="${y - height / 2}"
          width="${width}"
          height="${height}"
          fill="url(#${innerShadowId})"
          stroke="none"
          rx="12"
          opacity="0.3"
          pointer-events="none"
        />

        <!-- Cluster border - softer and more subtle -->
        <rect
          x="${x - width / 2}"
          y="${y - height / 2}"
          width="${width}"
          height="${height}"
          fill="none"
          stroke="${color}"
          stroke-width="${isHovered ? 2.5 : 2}"
          stroke-dasharray="6,6"
          rx="12"
          opacity="${isHovered ? 0.85 : 0.5}"
          style="transition: all 0.3s ease"
        />

        <!-- Cluster label -->
        <text
          x="${x}"
          y="${y - height / 2 - 8}"
          fill="${color}"
          text-anchor="middle"
          style="
            font-family: DM Sans, sans-serif;
            font-size: 14px;
            font-weight: var(--font-weight-medium);
            filter: ${isHovered ? 'url(#glow)' : 'none'};
            transition: filter 0.3s ease;
          "
        >
          ${clusterId}
        </text>
        <text
          x="${x}"
          y="${y - height / 2 + 7}"
          fill="${color}"
          text-anchor="middle"
          opacity="${isHovered ? 0.8 : 0.5}"
          style="
            font-family: Inter, sans-serif;
            font-size: 10px;
            transition: opacity 0.3s ease;
          "
        >
          ${origin === 'external' ? 'EXTERNAL' : 'LOCAL'} · ${nodeCount} targets
        </text>

        <!-- Content (edges and nodes) - slotted -->
        <slot></slot>
      </g>
    `;
  }
}

// Export for TypeScript type checking
declare global {
  interface HTMLElementTagNameMap {
    'graph-cluster': GraphCluster;
  }
}

// Register custom element with HMR support
if (!customElements.get('graph-cluster')) {
  customElements.define('graph-cluster', GraphCluster);
}
