// src/components/GraphVisualization.tsx
/**
 * Main graph visualization component
 * Refactored to use modular sub-components and custom hooks
 */

import { useCallback, useMemo, useRef, useState } from 'react';
import type { GraphEdge, GraphNode as GraphNodeType } from '../data/mockGraphData';
import type { ViewMode } from '../types/app';
import { ClusterGroup } from './graph/ClusterGroup';
import { GraphEdges } from './graph/GraphEdges';
import { GraphBackground, GraphControls, GraphEmptyState } from './graph/GraphOverlays';
import { GraphSVGDefs } from './graph/GraphSVGDefs';
import { LitGraphSVGDefs } from '../components-lit/wrappers/GraphSVGDefs';
import { useAnimatedLayout } from './graph/useAnimatedLayout';
import { useDeterministicLayout } from './graph/useDeterministicLayout';
import { useGraphInteraction } from './graph/useGraphInteraction';

interface GraphVisualizationProps {
  nodes: GraphNodeType[];
  edges: GraphEdge[];
  selectedNode: GraphNodeType | null;
  onNodeSelect: (node: GraphNodeType | null) => void;
  onClusterSelect: (clusterId: string | null) => void;
  searchQuery: string;
  viewMode: ViewMode;
  zoom: number;
  onZoomIn: () => void;
  onZoomOut: () => void;
  onZoomReset: () => void;
  transitiveDeps: {
    nodes: Set<string>;
    edges: Set<string>;
    edgeDepths: Map<string, number>;
    maxDepth: number;
  };
  transitiveDependents: {
    nodes: Set<string>;
    edges: Set<string>;
    edgeDepths: Map<string, number>;
    maxDepth: number;
  };
  enableAnimation: boolean;
  onToggleAnimation: (enabled: boolean) => void;
  selectedCluster?: string | null;
  hoveredNode: string | null;
  onNodeHover: (nodeId: string | null) => void;
  previewFilter?: {
    type: 'nodeType' | 'platform' | 'origin' | 'project' | 'package' | 'cluster';
    value: string;
  } | null;
}

export function GraphVisualization({
  nodes,
  edges,
  selectedNode,
  onNodeSelect,
  onClusterSelect,
  searchQuery,
  viewMode,
  zoom,
  onZoomIn,
  onZoomOut,
  onZoomReset,
  transitiveDeps,
  transitiveDependents,
  enableAnimation,
  onToggleAnimation,
  selectedCluster = null,
  hoveredNode,
  onNodeHover,
  previewFilter,
}: GraphVisualizationProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const svgRef = useRef<SVGSVGElement>(null);
  const [hoveredCluster, setHoveredCluster] = useState<string | null>(null);

  // Choose layout based on animation toggle
  const deterministicLayout = useDeterministicLayout(nodes, edges, {
    enableRelaxation: true,
    relaxationIterations: 30,
  });

  const animatedLayout = useAnimatedLayout(nodes, edges, {
    enableAnimation,
    animationTicks: 30,
  });

  // Use animated layout when enabled, otherwise deterministic
  const { nodePositions, clusterPositions, clusters } = enableAnimation
    ? animatedLayout
    : deterministicLayout;

  // Interaction handling (pan, zoom, drag)
  const {
    pan,
    isDragging,
    manualNodePositions,
    hasMoved,
    handleMouseDown,
    handleMouseMove,
    handleMouseUp,
    handleNodeMouseDown,
  } = useGraphInteraction({
    svgRef,
    zoom,
    finalNodePositions: nodePositions,
    clusterPositions,
  });

  // Merge manual positions with calculated positions
  const finalNodePositions = useMemo(() => {
    const merged = new Map(nodePositions);
    manualNodePositions.forEach((pos, id) => {
      const nodePos = merged.get(id);
      if (nodePos) {
        nodePos.x = pos.x;
        nodePos.y = pos.y;
      }
    });
    return merged;
  }, [nodePositions, manualNodePositions]);

  // Map clusters by ID for easy lookup
  const clustersById = useMemo(() => {
    const map = new Map();
    clusters.forEach((cluster) => {
      map.set(cluster.id, cluster);
    });
    return map;
  }, [clusters]);

  // Node click handler (memoized to prevent event listener re-attachment)
  const handleNodeClick = useCallback(
    (node: GraphNodeType, e: React.MouseEvent) => {
      e.stopPropagation();
      onNodeSelect(node);
    },
    [onNodeSelect],
  );

  // Canvas click handler - deselect node when clicking on background
  const handleCanvasClick = useCallback(
    (e: React.MouseEvent) => {
      // Don't deselect if we were panning (dragging the canvas)
      if (hasMoved) {
        return;
      }

      // Only deselect if clicking directly on the SVG background (not on nodes/clusters)
      if (e.target === e.currentTarget || (e.target as Element).closest('g.graph-background')) {
        onNodeSelect(null);
        onClusterSelect(null);
      }
    },
    [hasMoved, onNodeSelect, onClusterSelect],
  );

  // Wheel handler for zoom (memoized to prevent event listener re-attachment)
  const handleWheel = useCallback(
    (e: React.WheelEvent) => {
      // Only zoom if Ctrl/Cmd key is pressed (also captures trackpad pinch)
      if (!e.ctrlKey && !e.metaKey) {
        return;
      }

      e.preventDefault();

      // Determine zoom direction (negative deltaY = scroll up = zoom in)
      if (e.deltaY < 0) {
        onZoomIn();
      } else {
        onZoomOut();
      }
    },
    [onZoomIn, onZoomOut],
  );

  return (
    <div
      ref={containerRef}
      className="w-full h-full relative overflow-hidden"
      style={{
        backgroundColor: 'var(--color-background)',
        fontFamily: 'Inter, sans-serif',
      }}
      onMouseDown={handleMouseDown}
      onMouseMove={handleMouseMove}
      onMouseUp={handleMouseUp}
      onMouseLeave={handleMouseUp}
      onWheel={handleWheel}
    >
      {/* Background grid */}
      <GraphBackground />

      {/* Main SVG canvas */}
      <svg
        ref={svgRef}
        className="w-full h-full"
        style={{
          cursor: isDragging ? 'grabbing' : 'default',
        }}
        onClick={handleCanvasClick}
      >
        <LitGraphSVGDefs />

        <g transform={`translate(${pan.x}, ${pan.y}) scale(${zoom})`}>
          {/* Cross-cluster edges */}
          <g className="cluster-edges">
            <GraphEdges
              edges={edges}
              nodes={nodes}
              finalNodePositions={finalNodePositions}
              clusterPositions={clusterPositions}
              selectedNode={selectedNode}
              hoveredNode={hoveredNode}
              hoveredClusterId={hoveredCluster}
              viewMode={viewMode}
              transitiveDeps={transitiveDeps}
              transitiveDependents={transitiveDependents}
              zoom={zoom}
            />
          </g>

          {/* Clusters with their nodes and internal edges */}
          {Array.from(clusterPositions.entries()).map(([clusterId, clusterPos]) => {
            const cluster = clustersById.get(clusterId);
            if (!cluster) return null;

            return (
              <ClusterGroup
                key={clusterId}
                cluster={cluster}
                clusterPosition={clusterPos}
                nodes={nodes}
                edges={edges}
                finalNodePositions={finalNodePositions}
                selectedNode={selectedNode}
                hoveredNode={hoveredNode}
                hoveredClusterId={hoveredCluster}
                searchQuery={searchQuery}
                zoom={zoom}
                onNodeMouseEnter={onNodeHover}
                onNodeMouseLeave={() => onNodeHover(null)}
                onClusterMouseEnter={() => setHoveredCluster(clusterId)}
                onClusterMouseLeave={() => setHoveredCluster(null)}
                onNodeMouseDown={handleNodeMouseDown}
                onNodeClick={handleNodeClick}
                onClusterClick={() => onClusterSelect(clusterId)}
                viewMode={viewMode}
                transitiveDeps={transitiveDeps}
                transitiveDependents={transitiveDependents}
                isSelected={selectedCluster === clusterId}
                previewFilter={previewFilter}
              />
            );
          })}
        </g>
      </svg>

      {/* Overlays */}
      <GraphControls
        zoom={zoom}
        nodeCount={nodes.length}
        edgeCount={edges.length}
        onZoomIn={onZoomIn}
        onZoomOut={onZoomOut}
        onZoomReset={onZoomReset}
        enableAnimation={enableAnimation}
        onToggleAnimation={onToggleAnimation}
      />

      {/* Empty state */}
      {nodes.length === 0 && <GraphEmptyState />}
    </div>
  );
}

// src/components-lit/graph/graph-visualization.ts
/**
 * GraphVisualization Lit Component
 *
 * FULL graph rendering engine with:
 * - Animated layout with physics
 * - Deterministic layout option
 * - Pan/zoom/drag interactions
 * - Node dragging
 * - All graph features
 *
 * @example
 * ```html
 * <graph-visualization
 *   .nodes=${nodes}
 *   .edges=${edges}
 *   .selectedNode=${selectedNode}
 *   zoom="1.0"
 *   enable-animation
 * ></graph-visualization>
 * ```
 */

import { LitElement, html, css, svg } from 'lit';
import { state, query } from 'lit/decorators.js';
import type { GraphEdge, GraphNode as GraphNodeType } from '@/data/mockGraphData';
import type { ViewMode } from '@/types/app';
import { AnimatedLayoutController } from '@/controllers/animated-layout.controller';
import { GraphInteractionFullController } from '@/controllers/graph-interaction-full.controller';
import { computeHierarchicalLayout } from '@/utils/hierarchicalLayout';
import { groupIntoClusters } from '@/utils/clusterGrouping';
import { analyzeCluster } from '@/utils/clusterAnalysis';
import { renderClusterGroup } from './svg-renderers';
import './graph-svg-defs';
import './cluster-group';
import './graph-edges';
import '../graph/graph-overlays';

export class GraphVisualization extends LitElement {
  // ========================================
  // Properties
  // ========================================

  static properties = {
    nodes: { attribute: false },
    edges: { attribute: false },
    selectedNode: { attribute: false },
    selectedCluster: { attribute: false },
    hoveredNode: { attribute: false },
    searchQuery: { type: String, attribute: 'search-query' },
    viewMode: { type: String, attribute: 'view-mode' },
    zoom: { type: Number },
    enableAnimation: { type: Boolean, attribute: 'enable-animation' },
    transitiveDeps: { attribute: false },
    transitiveDependents: { attribute: false },
    previewFilter: { attribute: false },
  };

  declare nodes: GraphNodeType[] | undefined;
  declare edges: GraphEdge[] | undefined;
  declare selectedNode: GraphNodeType | null | undefined;
  declare selectedCluster: string | null | undefined;
  declare hoveredNode: string | null | undefined;
  declare searchQuery: string | undefined;
  declare viewMode: ViewMode | undefined;
  declare zoom: number | undefined;
  declare enableAnimation: boolean | undefined;
  declare transitiveDeps: any;
  declare transitiveDependents: any;
  declare previewFilter: any;

  // ========================================
  // Internal State
  // ========================================

  @state()
  private declare hoveredCluster: string | null;

  @query('svg')
  private svgElement!: SVGSVGElement;

  // ========================================
  // Controllers
  // ========================================

  private layout = new AnimatedLayoutController(this, {
    enableAnimation: this.enableAnimation,
    animationTicks: 30,
  });

  private interaction = new GraphInteractionFullController(this, {
    zoom: this.zoom,
    finalNodePositions: new Map(),
    clusterPositions: new Map(),
  });

  // ========================================
  // Styles
  // ========================================

  static styles = css`
    :host {
      display: block;
      position: relative;
      flex: 1;
      overflow: hidden;
      background-color: var(--color-background);
      min-height: 0;
      width: 100%;
      height: 100%;
    }

    svg {
      width: 100%;
      height: 100%;
      cursor: default;
    }

    svg.dragging {
      cursor: grabbing;
    }
  `;

  // ========================================
  // Lifecycle
  // ========================================

  updated(changedProps: Map<string, any>) {
    // Update layout when nodes/edges change
    if (changedProps.has('nodes') || changedProps.has('edges')) {
      this.layout.enableAnimation = this.enableAnimation;
      this.layout.computeLayout(this.nodes ?? [], this.edges ?? []);
    }

    // Update animation when enableAnimation changes
    if (changedProps.has('enableAnimation')) {
      this.layout.enableAnimation = this.enableAnimation;
    }

    // Update interaction config when zoom changes
    if (changedProps.has('zoom')) {
      this.interaction.updateConfig({
        zoom: this.zoom,
        finalNodePositions: this.finalNodePositions,
        clusterPositions: this.layout.clusterPositions,
      });
    }

    // Set SVG element reference
    if (this.svgElement && !this.interaction.hasSvgElement()) {
      this.interaction.setSvgElement(this.svgElement);
    }
  }

  // ========================================
  // Computed Values
  // ========================================

  private get finalNodePositions() {
    // Merge layout positions with manual positions
    const merged = new Map(this.layout.nodePositions);
    this.interaction.manualNodePositions.forEach((pos, id) => {
      const existing = merged.get(id);
      if (existing) {
        merged.set(id, { ...existing, x: pos.x, y: pos.y });
      }
    });
    return merged;
  }

  // ========================================
  // Event Handlers
  // ========================================

  private handleCanvasClick(e: MouseEvent) {
    // Only deselect if we didn't drag
    if (!this.interaction.hasMoved && (e.target as HTMLElement).tagName === 'svg') {
      this.dispatchEvent(
        new CustomEvent('node-select', {
          detail: { node: null },
          bubbles: true,
          composed: true,
        })
      );
      this.dispatchEvent(
        new CustomEvent('cluster-select', {
          detail: { clusterId: null },
          bubbles: true,
          composed: true,
        })
      );
    }
  }

  private handleNodeClick(e: CustomEvent) {
    if (!this.interaction.hasMoved) {
      this.dispatchEvent(
        new CustomEvent('node-select', {
          detail: e.detail,
          bubbles: true,
          composed: true,
        })
      );
    }
  }

  private handleWheel(e: WheelEvent) {
    // Only zoom if Ctrl/Cmd key is pressed (also captures trackpad pinch)
    if (!e.ctrlKey && !e.metaKey) {
      return;
    }

    e.preventDefault();

    const eventName = e.deltaY < 0 ? 'zoom-in' : 'zoom-out';
    this.dispatchEvent(
      new CustomEvent(eventName, {
        bubbles: true,
        composed: true,
      })
    );
  }

  // ========================================
  // Render
  // ========================================

  render() {
    return html`
      <graph-background></graph-background>

      <graph-controls
        .zoom=${this.zoom}
        node-count=${this.nodes?.length ?? 0}
        edge-count=${this.edges?.length ?? 0}
        ?enable-animation=${this.enableAnimation}
        @zoom-in=${() => this.dispatchEvent(new CustomEvent('zoom-in', { bubbles: true, composed: true }))}
        @zoom-out=${() =>
          this.dispatchEvent(new CustomEvent('zoom-out', { bubbles: true, composed: true }))}
        @zoom-reset=${() =>
          this.dispatchEvent(new CustomEvent('zoom-reset', { bubbles: true, composed: true }))}
        @toggle-animation=${() =>
          this.dispatchEvent(new CustomEvent('toggle-animation', { bubbles: true, composed: true }))}
      ></graph-controls>

      <svg
        class="${this.interaction.isDragging ? 'dragging' : ''}"
        @mousedown=${this.interaction.handleMouseDown}
        @mousemove=${this.interaction.handleMouseMove}
        @mouseup=${this.interaction.handleMouseUp}
        @mouseleave=${this.interaction.handleMouseUp}
        @click=${this.handleCanvasClick}
        @wheel=${this.handleWheel}
      >
        <graph-svg-defs></graph-svg-defs>

        <g transform="translate(${this.interaction.pan.x}, ${this.interaction.pan.y}) scale(${this.zoom ?? 1})">
          ${this.nodes?.length
            ? html`
                <!-- Cross-cluster edges -->
                <g class="cluster-edges">
                  <graph-edges
                    .edges=${this.edges}
                    .nodes=${this.nodes}
                    .finalNodePositions=${this.finalNodePositions}
                    .clusterPositions=${this.layout.clusterPositions}
                    .selectedNode=${this.selectedNode}
                    .hoveredNode=${this.hoveredNode}
                    .hoveredClusterId=${this.hoveredCluster}
                    view-mode=${this.viewMode}
                    .transitiveDeps=${this.transitiveDeps}
                    .transitiveDependents=${this.transitiveDependents}
                    .zoom=${this.zoom}
                  ></graph-edges>
                </g>

                <!-- Clusters with nodes and internal edges -->
                ${this.layout.clusters.map((cluster) => {
                  const position = this.layout.clusterPositions.get(cluster.id);
                  if (!position) return null;

                  const isSelected = this.selectedCluster === cluster.id;

                  return renderClusterGroup({
                    cluster,
                    clusterPosition: position,
                    nodes: this.nodes ?? [],
                    edges: this.edges ?? [],
                    finalNodePositions: this.finalNodePositions,
                    selectedNode: this.selectedNode ?? null,
                    hoveredNode: this.hoveredNode ?? null,
                    isClusterHovered: this.hoveredCluster === cluster.id,
                    isClusterSelected: isSelected,
                    searchQuery: this.searchQuery,
                    zoom: this.zoom,
                    previewFilter: this.previewFilter,
                    onClusterClick: () =>
                      this.dispatchEvent(
                        new CustomEvent('cluster-select', {
                          detail: { clusterId: cluster.id },
                          bubbles: true,
                          composed: true,
                        })
                      ),
                    onClusterMouseEnter: () => (this.hoveredCluster = cluster.id),
                    onClusterMouseLeave: () => (this.hoveredCluster = null),
                    onNodeMouseEnter: (nodeId) =>
                      this.dispatchEvent(
                        new CustomEvent('node-hover', {
                          detail: { nodeId },
                          bubbles: true,
                          composed: true,
                        })
                      ),
                    onNodeMouseLeave: () =>
                      this.dispatchEvent(
                        new CustomEvent('node-hover', {
                          detail: { nodeId: null },
                          bubbles: true,
                          composed: true,
                        })
                      ),
                    onNodeMouseDown: (nodeId, e) =>
                      this.interaction.handleNodeMouseDown(nodeId, e),
                    onNodeClick: (node, e) => {
                      if (!this.interaction.hasMoved) {
                        this.dispatchEvent(
                          new CustomEvent('node-select', {
                            detail: { node },
                            bubbles: true,
                            composed: true,
                          })
                        );
                      }
                    },
                  });
                })}
              `
            : ''}
        </g>
      </svg>

      ${this.nodes?.length === 0
        ? html`<graph-visualization-empty-state></graph-visualization-empty-state>`
        : ''}
    `;
  }
}

// Export for TypeScript type checking
declare global {
  interface HTMLElementTagNameMap {
    'graph-visualization': GraphVisualization;
  }
}

// Register custom element with HMR support
if (!customElements.get('graph-visualization')) {
  customElements.define('graph-visualization', GraphVisualization);
}
