// src/components/layout/GraphTab.tsx
/**
 * Graph tab content component
 * Extracted from App.tsx for better modularity
 * Uses design system CSS variables
 * Reads state from Zustand stores
 */

import type { GraphEdge, GraphNode } from '../../data/mockGraphData';
import { useGraphStore } from '../../stores/graphStore';
import { useFilterStore } from '../../stores/filterStore';
import { useUIStore } from '../../stores/uiStore';
import { GraphVisualization } from '../../components-lit/wrappers/GraphVisualization';
import { RightSidebar } from '../../components-lit/wrappers/RightSidebar';
import { Toolbar } from './Toolbar';

interface GraphTabProps {
  // Data - still passed as props (computed in App)
  displayNodes: GraphNode[];
  displayEdges: GraphEdge[];
  filteredNodes: GraphNode[];
  filteredEdges: GraphEdge[];
  allNodes: GraphNode[];
  allEdges: GraphEdge[];

  // Depth information for edge opacity (computed in App)
  transitiveDeps: {
    nodes: Set<string>;
    edges: Set<string>;
    edgeDepths: Map<string, number>;
    maxDepth: number;
  };
  transitiveDependents: {
    nodes: Set<string>;
    edges: Set<string>;
    edgeDepths: Map<string, number>;
    maxDepth: number;
  };
}

export function GraphTab({
  displayNodes,
  displayEdges,
  filteredNodes,
  filteredEdges,
  allNodes,
  allEdges,
  transitiveDeps,
  transitiveDependents,
}: GraphTabProps) {
  // Graph store - only what GraphVisualization needs
  const selectedNode = useGraphStore((s) => s.selectedNode);
  const selectedCluster = useGraphStore((s) => s.selectedCluster);
  const hoveredNode = useGraphStore((s) => s.hoveredNode);
  const viewMode = useGraphStore((s) => s.viewMode);
  const selectNode = useGraphStore((s) => s.selectNode);
  const selectCluster = useGraphStore((s) => s.selectCluster);
  const setHoveredNode = useGraphStore((s) => s.setHoveredNode);

  // Filter store - only searchQuery for GraphVisualization
  const searchQuery = useFilterStore((s) => s.searchQuery);

  // UI store - for Toolbar and GraphVisualization
  const zoom = useUIStore((s) => s.zoom);
  const enableAnimation = useUIStore((s) => s.enableAnimation);
  const previewFilter = useUIStore((s) => s.previewFilter);
  const zoomIn = useUIStore((s) => s.zoomIn);
  const zoomOut = useUIStore((s) => s.zoomOut);
  const resetZoom = useUIStore((s) => s.resetZoom);
  const setEnableAnimation = useUIStore((s) => s.setEnableAnimation);

  return (
    <div className="flex-1 flex overflow-hidden">
      <div className="flex-1 flex flex-col overflow-hidden">
        {/* Toolbar */}
        <Toolbar
          zoom={zoom}
          onZoomIn={zoomIn}
          onZoomOut={zoomOut}
          onZoomReset={resetZoom}
          nodeCount={filteredNodes.length}
          edgeCount={filteredEdges.length}
        />

        {/* Graph + Right Sidebar */}
        <div className="flex-1 flex overflow-hidden relative">
          {/* Graph Visualization */}
          <div className="flex-1 relative">
            <GraphVisualization
              nodes={displayNodes}
              edges={displayEdges}
              selectedNode={selectedNode}
              selectedCluster={selectedCluster}
              hoveredNode={hoveredNode}
              searchQuery={searchQuery}
              viewMode={viewMode}
              zoom={zoom}
              enableAnimation={enableAnimation}
              transitiveDeps={transitiveDeps}
              transitiveDependents={transitiveDependents}
              previewFilter={previewFilter}
              onNodeSelect={(e) => selectNode(e.detail.node)}
              onClusterSelect={(e) => selectCluster(e.detail.clusterId)}
              onNodeHover={(e) => setHoveredNode(e.detail.nodeId)}
              onZoomIn={() => zoomIn()}
              onZoomOut={() => zoomOut()}
              onZoomReset={() => resetZoom()}
              onToggleAnimation={() => setEnableAnimation(!enableAnimation)}
            />
          </div>

          {/* Right Sidebar with Filters and Node/Cluster Details */}
          <RightSidebar
            allNodes={allNodes}
            allEdges={allEdges}
            filteredNodes={filteredNodes}
            filteredEdges={filteredEdges}
          />
        </div>
      </div>
    </div>
  );
}

// src/components-lit/layout/graph-tab.ts
/**
 * GraphTab Lit Component
 *
 * Main graph tab orchestrator - coordinates GraphVisualization and RightSidebar.
 * Uses Zustand stores for state management.
 *
 * @example
 * ```html
 * <graph-tab
 *   .displayNodes=${nodes}
 *   .displayEdges=${edges}
 *   .allNodes=${allNodes}
 * ></graph-tab>
 * ```
 */

import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import type { GraphEdge, GraphNode } from '@/data/mockGraphData';
import { createStoreController } from '@/controllers/zustand.controller';
import { useGraphStore } from '@/stores/graphStore';
import { useFilterStore } from '@/stores/filterStore';
import { useUIStore } from '@/stores/uiStore';
import '../graph/graph-visualization';
import '../ui/right-sidebar';

@customElement('graph-tab')
export class GraphTab extends LitElement {
  // ========================================
  // Properties
  // ========================================

  @property({ attribute: false })
  declare displayNodes: GraphNode[];

  @property({ attribute: false })
  declare displayEdges: GraphEdge[];

  @property({ attribute: false })
  declare filteredNodes: GraphNode[];

  @property({ attribute: false })
  declare filteredEdges: GraphEdge[];

  @property({ attribute: false })
  declare allNodes: GraphNode[];

  @property({ attribute: false })
  declare allEdges: GraphEdge[];

  @property({ attribute: false })
  declare transitiveDeps: any;

  @property({ attribute: false })
  declare transitiveDependents: any;

  // ========================================
  // Zustand Store Subscriptions
  // ========================================

  // Graph store
  private selectedNode = createStoreController(this, useGraphStore, (s) => s.selectedNode);
  private selectedCluster = createStoreController(this, useGraphStore, (s) => s.selectedCluster);
  private hoveredNode = createStoreController(this, useGraphStore, (s) => s.hoveredNode);
  private viewMode = createStoreController(this, useGraphStore, (s) => s.viewMode);

  // Filter store
  private searchQuery = createStoreController(this, useFilterStore, (s) => s.searchQuery);

  // UI store
  private zoom = createStoreController(this, useUIStore, (s) => s.zoom);
  private enableAnimation = createStoreController(this, useUIStore, (s) => s.enableAnimation);
  private previewFilter = createStoreController(this, useUIStore, (s) => s.previewFilter);

  // ========================================
  // Styles
  // ========================================

  static styles = css`
    :host {
      display: flex;
      flex: 1;
      overflow: hidden;
    }

    .container {
      display: flex;
      flex: 1;
      flex-direction: column;
      overflow: hidden;
    }

    .content {
      display: flex;
      flex: 1;
      overflow: hidden;
      position: relative;
    }

    .graph-container {
      flex: 1;
      position: relative;
    }
  `;

  // ========================================
  // Event Handlers (delegate to stores)
  // ========================================

  private handleNodeSelect(e: CustomEvent) {
    const selectNode = this.selectedNode.getAction('selectNode');
    selectNode(e.detail.node);
  }

  private handleClusterSelect(e: CustomEvent) {
    const selectCluster = this.selectedCluster.getAction('selectCluster');
    selectCluster(e.detail.clusterId);
  }

  private handleNodeHover(e: CustomEvent) {
    const setHoveredNode = this.hoveredNode.getAction('setHoveredNode');
    setHoveredNode(e.detail.nodeId);
  }

  private handleZoomIn() {
    const zoomIn = this.zoom.getAction('zoomIn');
    zoomIn();
  }

  private handleZoomOut() {
    const zoomOut = this.zoom.getAction('zoomOut');
    zoomOut();
  }

  private handleZoomReset() {
    const resetZoom = this.zoom.getAction('resetZoom');
    resetZoom();
  }

  private handleToggleAnimation() {
    const toggleAnimation = this.enableAnimation.getAction('toggleAnimation');
    toggleAnimation();
  }

  // ========================================
  // Render
  // ========================================

  render() {
    return html`
      <div class="container">
        <!-- Graph + Sidebar -->
        <div class="content">
          <!-- Graph Visualization -->
          <div class="graph-container">
            <graph-visualization
              .nodes=${this.displayNodes}
              .edges=${this.displayEdges}
              .selectedNode=${this.selectedNode.value}
              .selectedCluster=${this.selectedCluster.value}
              .hoveredNode=${this.hoveredNode.value}
              search-query=${this.searchQuery.value || ''}
              view-mode=${this.viewMode.value}
              .zoom=${this.zoom.value}
              ?enable-animation=${this.enableAnimation.value}
              .transitiveDeps=${this.transitiveDeps}
              .transitiveDependents=${this.transitiveDependents}
              .previewFilter=${this.previewFilter.value}
              @node-select=${this.handleNodeSelect}
              @cluster-select=${this.handleClusterSelect}
              @node-hover=${this.handleNodeHover}
              @zoom-in=${this.handleZoomIn}
              @zoom-out=${this.handleZoomOut}
              @zoom-reset=${this.handleZoomReset}
              @toggle-animation=${this.handleToggleAnimation}
            ></graph-visualization>
          </div>

          <!-- Right Sidebar -->
          <graph-right-sidebar
            .allNodes=${this.allNodes}
            .allEdges=${this.allEdges}
            .filteredNodes=${this.filteredNodes}
            .filteredEdges=${this.filteredEdges}
          ></graph-right-sidebar>
        </div>
      </div>
    `;
  }
}

// Export for TypeScript type checking
declare global {
  interface HTMLElementTagNameMap {
    'graph-tab': GraphTab;
  }
}
