// src/components/ui/accordion.tsx
'use client';

import { ChevronDownIcon } from 'lucide-react@0.487.0';
import * as AccordionPrimitive from '@radix-ui/react-accordion@1.2.3';
import type * as React from 'react';

import { cn } from './utils';

function Accordion({ ...props }: React.ComponentProps<typeof AccordionPrimitive.Root>) {
  return <AccordionPrimitive.Root data-slot="accordion" {...props} />;
}

function AccordionItem({
  className,
  ...props
}: React.ComponentProps<typeof AccordionPrimitive.Item>) {
  return (
    <AccordionPrimitive.Item
      data-slot="accordion-item"
      className={cn('border-b last:border-b-0', className)}
      {...props}
    />
  );
}

function AccordionTrigger({
  className,
  children,
  ...props
}: React.ComponentProps<typeof AccordionPrimitive.Trigger>) {
  return (
    <AccordionPrimitive.Header className="flex">
      <AccordionPrimitive.Trigger
        data-slot="accordion-trigger"
        className={cn(
          'focus-visible:border-ring focus-visible:ring-ring/50 flex flex-1 items-start justify-between gap-4 rounded-md py-4 text-left text-sm font-medium transition-all outline-none hover:underline focus-visible:ring-[3px] disabled:pointer-events-none disabled:opacity-50 [&[data-state=open]>svg]:rotate-180',
          className,
        )}
        {...props}
      >
        {children}
        <ChevronDownIcon className="text-muted-foreground pointer-events-none size-4 shrink-0 translate-y-0.5 transition-transform duration-200" />
      </AccordionPrimitive.Trigger>
    </AccordionPrimitive.Header>
  );
}

function AccordionContent({
  className,
  children,
  ...props
}: React.ComponentProps<typeof AccordionPrimitive.Content>) {
  return (
    <AccordionPrimitive.Content
      data-slot="accordion-content"
      className="data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down overflow-hidden text-sm"
      {...props}
    >
      <div className={cn('pt-0 pb-4', className)}>{children}</div>
    </AccordionPrimitive.Content>
  );
}

export { Accordion, AccordionItem, AccordionTrigger, AccordionContent };

// src/components-lit/ui/accordion.ts
import { LitElement, html, css, svg } from 'lit';

export class GraphAccordion extends LitElement {
  static override properties = {
    value: { type: String },
    type: { type: String },
  };

  static override styles = css`
    :host {
      display: block;
    }
  `;

  declare value: string;
  declare type: 'single' | 'multiple';

  constructor() {
    super();
    this.value = '';
    this.type = 'single';
  }

  private handleItemToggle(e: CustomEvent<{ value: string; open: boolean }>) {
    if (this.type === 'single') {
      this.value = e.detail.open ? e.detail.value : '';
    }

    this.dispatchEvent(
      new CustomEvent('accordion-change', {
        detail: { value: e.detail.value, open: e.detail.open },
        bubbles: true,
        composed: true,
      })
    );
  }

  protected override render() {
    return html`<slot @accordion-item-toggle=${this.handleItemToggle}></slot>`;
  }
}

export class GraphAccordionItem extends LitElement {
  static override properties = {
    value: { type: String },
    open: { type: Boolean, reflect: true },
  };

  static override styles = css`
    :host {
      border-bottom: 1px solid var(--colors-border);
    }

    :host(:last-child) {
      border-bottom: none;
    }
  `;

  declare value: string;
  declare open: boolean;

  constructor() {
    super();
    this.value = '';
    this.open = false;
  }

  private handleToggle() {
    this.open = !this.open;

    this.dispatchEvent(
      new CustomEvent('accordion-item-toggle', {
        detail: { value: this.value, open: this.open },
        bubbles: true,
        composed: true,
      })
    );
  }

  protected override render() {
    return html`<slot @accordion-trigger-click=${this.handleToggle}></slot>`;
  }
}

export class GraphAccordionTrigger extends LitElement {
  static override properties = {
    open: { type: Boolean, reflect: true },
    disabled: { type: Boolean, reflect: true },
  };

  static override styles = css`
    button {
      display: flex;
      flex: 1;
      align-items: start;
      justify-content: space-between;
      gap: 16px;
      border-radius: var(--radii-md);
      padding-block: 16px;
      text-align: left;
      font-size: var(--font-sizes-sm);
      font-weight: var(--font-weights-medium);
      transition: all 150ms;
      cursor: pointer;
      outline: none;
      border: none;
      background: transparent;
      width: 100%;
    }

    button:hover {
      text-decoration: underline;
    }

    button:focus-visible {
      box-shadow: 0 0 0 3px rgba(111, 44, 255, 0.5);
    }

    button:disabled {
      pointer-events: none;
      opacity: 0.5;
    }

    .icon {
      color: var(--colors-muted-foreground);
      pointer-events: none;
      flex-shrink: 0;
      transition: transform 200ms;
    }

    :host([open]) .icon {
      transform: rotate(180deg);
    }
  `;

  declare open: boolean;
  declare disabled: boolean;

  constructor() {
    super();
    this.open = false;
    this.disabled = false;
  }

  private handleClick() {
    if (this.disabled) return;

    this.dispatchEvent(
      new CustomEvent('accordion-trigger-click', {
        bubbles: true,
        composed: true,
      })
    );
  }

  protected override render() {
    return html`
      <button
        type="button"
        data-slot="accordion-trigger"
        data-state=${this.open ? 'open' : 'closed'}
        @click=${this.handleClick}
      >
        <slot></slot>
        ${svg`
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="icon">
            <polyline points="6 9 12 15 18 9"/>
          </svg>
        `}
      </button>
    `;
  }
}

export class GraphAccordionContent extends LitElement {
  static override properties = {
    open: { type: Boolean, reflect: true },
  };

  static override styles = css`
    :host {
      overflow: hidden;
      font-size: var(--font-sizes-sm);
      transition: all 150ms;
    }

    :host(:not([open])) {
      display: none;
    }

    .content {
      padding-top: 0;
      padding-bottom: 16px;
    }
  `;

  declare open: boolean;

  constructor() {
    super();
    this.open = false;
  }

  protected override render() {
    return html`
      <div class="content" data-slot="accordion-content" data-state=${this.open ? 'open' : 'closed'}>
        <slot></slot>
      </div>
    `;
  }
}

customElements.define('graph-accordion', GraphAccordion);
customElements.define('graph-accordion-item', GraphAccordionItem);
customElements.define('graph-accordion-trigger', GraphAccordionTrigger);
customElements.define('graph-accordion-content', GraphAccordionContent);

declare global {
  interface HTMLElementTagNameMap {
    'graph-accordion': GraphAccordion;
    'graph-accordion-item': GraphAccordionItem;
    'graph-accordion-trigger': GraphAccordionTrigger;
    'graph-accordion-content': GraphAccordionContent;
  }
}
