// src/components/sidebar/EmptyState.tsx
interface EmptyStateProps {
  hasActiveFilters: boolean;
  onClearFilters: () => void;
}

export function EmptyState({ hasActiveFilters, onClearFilters }: EmptyStateProps) {
  return (
    <div className="px-4 py-8 text-center">
      <div
        className="mb-2"
        style={{
          fontFamily: 'Inter, sans-serif',
          fontSize: 'var(--text-base)',
          fontWeight: 'var(--font-weight-medium)',
          color: 'var(--color-foreground)'
        }}
      >
        No nodes match filters
      </div>
      <div
        style={{
          fontFamily: 'Inter, sans-serif',
          fontSize: 'var(--text-small)',
          color: 'var(--color-muted-foreground)',
          marginBottom: 'var(--spacing-md)'
        }}
      >
        Try adjusting your filter settings
      </div>
      {hasActiveFilters && (
        <button
          onClick={onClearFilters}
          className="px-4 py-2 rounded-lg transition-smooth-fast hover:bg-[rgba(255,255,255,0.05)]"
          style={{
            backgroundColor: 'rgba(168, 157, 255, 0.1)',
            border: '1px solid rgba(168, 157, 255, 0.3)',
            fontFamily: 'Inter, sans-serif',
            fontSize: 'var(--text-label)',
            color: 'rgba(168, 157, 255, 1)',
            fontWeight: 'var(--font-weight-medium)',
            borderRadius: 'var(--radius)'
          }}
        >
          Clear all filters
        </button>
      )}
    </div>
  );
}

// src/components-lit/ui/empty-state.ts
/**
 * EmptyState Lit Component
 *
 * Displays an empty state message when no nodes match the current filters.
 * Shows optional "Clear all filters" button when filters are active.
 *
 * @example
 * ```html
 * <graph-empty-state has-active-filters></graph-empty-state>
 * ```
 *
 * @fires clear-filters - Dispatched when clear button is clicked
 */

import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';

@customElement('graph-empty-state')
export class GraphEmptyState extends LitElement {
  // ========================================
  // Properties
  // ========================================

  /**
   * Whether there are active filters that can be cleared
   */
  @property({ type: Boolean, attribute: 'has-active-filters' })
  declare hasActiveFilters: boolean;

  // ========================================
  // Styles
  // ========================================

  static styles = css`
    :host {
      display: block;
      padding: var(--spacing-lg) var(--spacing-md);
      text-align: center;
    }

    .title {
      margin-bottom: var(--spacing-xs);
      font-family: 'Inter', sans-serif;
      font-size: var(--text-base);
      font-weight: var(--font-weight-medium);
      color: var(--color-foreground);
    }

    .description {
      font-family: 'Inter', sans-serif;
      font-size: var(--text-small);
      color: var(--color-muted-foreground);
      margin-bottom: var(--spacing-md);
    }

    .clear-button {
      padding: var(--spacing-sm) var(--spacing-md);
      border-radius: var(--radius-lg);
      transition: background-color 0.2s ease;
      background-color: rgba(168, 157, 255, 0.1);
      border: 1px solid rgba(168, 157, 255, 0.3);
      font-family: 'Inter', sans-serif;
      font-size: var(--text-label);
      color: rgba(168, 157, 255, 1);
      font-weight: var(--font-weight-medium);
      cursor: pointer;
    }

    .clear-button:hover {
      background-color: rgba(255, 255, 255, 0.05);
    }
  `;

  // ========================================
  // Event Handlers
  // ========================================

  private handleClearFilters() {
    this.dispatchEvent(
      new CustomEvent('clear-filters', {
        bubbles: true,
        composed: true,
      })
    );
  }

  // ========================================
  // Render
  // ========================================

  render() {
    return html`
      <div class="title">No nodes match filters</div>
      <div class="description">Try adjusting your filter settings</div>
      ${this.hasActiveFilters
        ? html`
            <button class="clear-button" @click=${this.handleClearFilters}>
              Clear all filters
            </button>
          `
        : ''}
    `;
  }
}

// Export for TypeScript type checking
declare global {
  interface HTMLElementTagNameMap {
    'graph-empty-state': GraphEmptyState;
  }
}
