// src/components/nodeDetails/NodeInfo.tsx
/**
 * Node info section component - displays key-value pairs about the node
 */

import type { GraphNode } from '../../data/mockGraphData';
import { getNodeTypeLabel } from '../../utils/nodeIcons';

interface NodeInfoProps {
  node: GraphNode;
}

export function NodeInfo({ node }: NodeInfoProps) {
  return (
    <div className="p-4 mt-auto">
      {/* Section Title */}
      <div
        className="mb-3"
        style={{
          fontFamily: 'Inter, sans-serif',
          fontSize: 'var(--text-label)',
          color: 'var(--color-muted-foreground)',
        }}
      >
        Node Info
      </div>

      {/* Info Rows */}
      <div className="flex flex-col gap-2">
        {/* Platform */}
        <div className="flex items-center justify-between">
          <span
            style={{
              fontFamily: 'Inter, sans-serif',
              fontSize: 'var(--text-label)',
              color: 'var(--color-muted-foreground)',
            }}
          >
            Platform:
          </span>
          <span
            style={{
              fontFamily: 'Inter, sans-serif',
              fontSize: 'var(--text-label)',
              color: 'var(--color-foreground)',
            }}
          >
            {node.platform}
          </span>
        </div>

        {/* Origin */}
        <div className="flex items-center justify-between">
          <span
            style={{
              fontFamily: 'Inter, sans-serif',
              fontSize: 'var(--text-label)',
              color: 'var(--color-muted-foreground)',
            }}
          >
            Origin:
          </span>
          <span
            style={{
              fontFamily: 'Inter, sans-serif',
              fontSize: 'var(--text-label)',
              color: 'var(--color-foreground)',
            }}
          >
            {node.origin === 'local' ? 'Local Project' : 'External Package'}
          </span>
        </div>

        {/* Type */}
        <div className="flex items-center justify-between">
          <span
            style={{
              fontFamily: 'Inter, sans-serif',
              fontSize: 'var(--text-label)',
              color: 'var(--color-muted-foreground)',
            }}
          >
            Type:
          </span>
          <span
            style={{
              fontFamily: 'Inter, sans-serif',
              fontSize: 'var(--text-label)',
              color: 'var(--color-foreground)',
            }}
          >
            {getNodeTypeLabel(node.type)}
          </span>
        </div>
      </div>
    </div>
  );
}

// src/components-lit/ui/node-info.ts
/**
 * NodeInfo Lit Component
 *
 * Displays key-value pairs about a node (platform, origin, type).
 *
 * @example
 * ```html
 * <graph-node-info .node=${nodeData}></graph-node-info>
 * ```
 */

import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import type { GraphNode } from '@/data/mockGraphData';
import { getNodeTypeLabel } from '@/utils/nodeIcons';

@customElement('graph-node-info')
export class GraphNodeInfo extends LitElement {
  // ========================================
  // Properties
  // ========================================

  @property({ attribute: false })
  declare node: GraphNode;

  // ========================================
  // Styles
  // ========================================

  static styles = css`
    :host {
      display: block;
      padding: var(--spacing-md);
      margin-top: auto;
    }

    .title {
      margin-bottom: 12px;
      font-family: 'Inter', sans-serif;
      font-size: var(--text-label);
      color: var(--color-muted-foreground);
    }

    .info-rows {
      display: flex;
      flex-direction: column;
      gap: 8px;
    }

    .info-row {
      display: flex;
      align-items: center;
      justify-content: space-between;
    }

    .info-label {
      font-family: 'Inter', sans-serif;
      font-size: var(--text-label);
      color: var(--color-muted-foreground);
    }

    .info-value {
      font-family: 'Inter', sans-serif;
      font-size: var(--text-label);
      color: var(--color-foreground);
    }
  `;

  // ========================================
  // Helpers
  // ========================================

  private get originLabel(): string {
    return this.node.origin === 'local' ? 'Local Project' : 'External Package';
  }

  // ========================================
  // Render
  // ========================================

  render() {
    if (!this.node) return html``;

    return html`
      <div class="title">Node Info</div>

      <div class="info-rows">
        <!-- Platform -->
        <div class="info-row">
          <span class="info-label">Platform:</span>
          <span class="info-value">${this.node.platform}</span>
        </div>

        <!-- Origin -->
        <div class="info-row">
          <span class="info-label">Origin:</span>
          <span class="info-value">${this.originLabel}</span>
        </div>

        <!-- Type -->
        <div class="info-row">
          <span class="info-label">Type:</span>
          <span class="info-value">${getNodeTypeLabel(this.node.type)}</span>
        </div>
      </div>
    `;
  }
}

// Export for TypeScript type checking
declare global {
  interface HTMLElementTagNameMap {
    'graph-node-info': GraphNodeInfo;
  }
}
