// src/components/sidebar/RightSidebarHeader.tsx
/**
 * Right sidebar header with collapse button
 * All styling uses design system CSS variables
 */

import { SidebarCollapseIcon } from './icons/SidebarCollapseIcon';
import { SidebarCollapseIcon as LitSidebarCollapseIcon } from '../../components-lit/wrappers/SidebarCollapseIcon';

interface RightSidebarHeaderProps {
  title: string;
  isCollapsed: boolean;
  onToggleCollapse: () => void;
}

export function RightSidebarHeader({
  title,
  isCollapsed,
  onToggleCollapse,
}: RightSidebarHeaderProps) {
  return (
    <div
      className="px-4 py-3 shrink-0 flex items-center justify-between"
      style={{ borderBottom: '1px solid var(--color-sidebar-border)' }}
    >
      {!isCollapsed && (
        <h2
          style={{
            fontFamily: 'DM Sans, sans-serif',
            fontSize: 'var(--text-h2)',
            fontWeight: 'var(--font-weight-medium)',
            color: 'var(--color-foreground)',
          }}
        >
          {title}
        </h2>
      )}
      <button
        onClick={onToggleCollapse}
        className="p-1.5 rounded-lg transition-smooth-fast hover:bg-[var(--color-muted)] ml-auto"
        style={{
          color: 'var(--color-muted-foreground)',
          borderRadius: 'var(--radius)',
        }}
        title={isCollapsed ? 'Expand sidebar' : 'Collapse sidebar'}
      >
        <LitSidebarCollapseIcon isCollapsed={isCollapsed} />
      </button>
    </div>
  );
}

// src/components-lit/ui/right-sidebar-header.ts
/**
 * RightSidebarHeader Lit Component
 *
 * Header for right sidebar with title and collapse button.
 * Already uses LitSidebarCollapseIcon.
 *
 * @example
 * ```html
 * <graph-right-sidebar-header
 *   title="Filters"
 *   is-collapsed
 * ></graph-right-sidebar-header>
 * ```
 *
 * @fires toggle-collapse - Dispatched when collapse button is clicked
 */

import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import '../ui/sidebar-collapse-icon';

@customElement('graph-right-sidebar-header')
export class GraphRightSidebarHeader extends LitElement {
  // ========================================
  // Properties
  // ========================================

  @property({ type: String })
  declare title: string;

  @property({ type: Boolean, attribute: 'is-collapsed' })
  declare isCollapsed: boolean;

  // ========================================
  // Styles
  // ========================================

  static styles = css`
    :host {
      display: block;
      padding: 12px var(--spacing-md);
      flex-shrink: 0;
      border-bottom: 1px solid var(--color-sidebar-border);
    }

    .container {
      display: flex;
      align-items: center;
      justify-content: space-between;
    }

    .title {
      font-family: 'DM Sans', sans-serif;
      font-size: var(--text-h2);
      font-weight: var(--font-weight-medium);
      color: var(--color-foreground);
    }

    .toggle-button {
      padding: 6px;
      border-radius: var(--radius-lg);
      transition: background-color 0.2s;
      background: none;
      border: none;
      color: var(--color-muted-foreground);
      cursor: pointer;
      margin-left: auto;
    }

    .toggle-button:hover {
      background-color: var(--color-muted);
    }
  `;

  // ========================================
  // Event Handlers
  // ========================================

  private handleToggle() {
    this.dispatchEvent(
      new CustomEvent('toggle-collapse', {
        bubbles: true,
        composed: true,
      })
    );
  }

  // ========================================
  // Render
  // ========================================

  render() {
    return html`
      <div class="container">
        ${!this.isCollapsed ? html`<h2 class="title">${this.title}</h2>` : ''}
        <button
          class="toggle-button"
          @click=${this.handleToggle}
          title="${this.isCollapsed ? 'Expand sidebar' : 'Collapse sidebar'}"
        >
          <graph-sidebar-collapse-icon ?is-collapsed=${this.isCollapsed}></graph-sidebar-collapse-icon>
        </button>
      </div>
    `;
  }
}

// Export for TypeScript type checking
declare global {
  interface HTMLElementTagNameMap {
    'graph-right-sidebar-header': GraphRightSidebarHeader;
  }
}
