// src/components/ui/slider.tsx
'use client';

import * as SliderPrimitive from '@radix-ui/react-slider@1.2.3';
import * as React from 'react';

import { cn } from './utils';

function Slider({
  className,
  defaultValue,
  value,
  min = 0,
  max = 100,
  ...props
}: React.ComponentProps<typeof SliderPrimitive.Root>) {
  const _values = React.useMemo(
    () => (Array.isArray(value) ? value : Array.isArray(defaultValue) ? defaultValue : [min, max]),
    [value, defaultValue, min, max],
  );

  return (
    <SliderPrimitive.Root
      data-slot="slider"
      defaultValue={defaultValue}
      value={value}
      min={min}
      max={max}
      className={cn(
        'relative flex w-full touch-none items-center select-none data-[disabled]:opacity-50 data-[orientation=vertical]:h-full data-[orientation=vertical]:min-h-44 data-[orientation=vertical]:w-auto data-[orientation=vertical]:flex-col',
        className,
      )}
      {...props}
    >
      <SliderPrimitive.Track
        data-slot="slider-track"
        className={cn(
          'bg-muted relative grow overflow-hidden rounded-full data-[orientation=horizontal]:h-4 data-[orientation=horizontal]:w-full data-[orientation=vertical]:h-full data-[orientation=vertical]:w-1.5',
        )}
      >
        <SliderPrimitive.Range
          data-slot="slider-range"
          className={cn(
            'bg-primary absolute data-[orientation=horizontal]:h-full data-[orientation=vertical]:w-full',
          )}
        />
      </SliderPrimitive.Track>
      {Array.from({ length: _values.length }, (_, index) => (
        <SliderPrimitive.Thumb
          data-slot="slider-thumb"
          key={index}
          className="border-primary bg-background ring-ring/50 block size-4 shrink-0 rounded-full border shadow-sm transition-[color,box-shadow] hover:ring-4 focus-visible:ring-4 focus-visible:outline-hidden disabled:pointer-events-none disabled:opacity-50"
        />
      ))}
    </SliderPrimitive.Root>
  );
}

export { Slider };

// src/components-lit/ui/slider.ts
import { LitElement, html, css } from 'lit';

/**
 * Graph Slider - A Lit Web Component for range sliders
 *
 * Accessible slider with keyboard support and ARIA.
 * Uses Shadow DOM with CSS custom properties.
 */
export class GraphSlider extends LitElement {
  static override properties = {
    min: { type: Number },
    max: { type: Number },
    step: { type: Number },
    value: { type: Number },
    disabled: { type: Boolean, reflect: true },
  };

  static override styles = css`
    :host {
      display: block;
      width: 100%;
      position: relative;
    }

    .container {
      position: relative;
      display: flex;
      width: 100%;
      touch-action: none;
      align-items: center;
      user-select: none;
      cursor: pointer;
    }

    :host([disabled]) .container {
      opacity: 0.5;
      cursor: not-allowed;
    }

    .track {
      position: relative;
      flex-grow: 1;
      overflow: hidden;
      border-radius: 9999px;
      background-color: var(--colors-muted);
      height: 4px;
    }

    .range {
      position: absolute;
      background-color: var(--colors-primary);
      height: 100%;
    }

    .thumb {
      position: absolute;
      display: block;
      width: 16px;
      height: 16px;
      flex-shrink: 0;
      border-radius: 9999px;
      border: 1px solid var(--colors-primary);
      background-color: var(--colors-background);
      box-shadow: var(--elevation-sm);
      transition: colors 150ms;
      pointer-events: none;
    }

    input {
      position: absolute;
      width: 100%;
      height: 100%;
      opacity: 0;
      cursor: pointer;
      margin: 0;
    }

    input:disabled {
      cursor: not-allowed;
    }

    input:focus-visible + .thumb {
      box-shadow: 0 0 0 4px rgba(111, 44, 255, 0.5);
      outline: none;
    }
  `;

  declare min: number;
  declare max: number;
  declare step: number;
  declare value: number;
  declare disabled: boolean;

  constructor() {
    super();
    this.min = 0;
    this.max = 100;
    this.step = 1;
    this.value = 50;
    this.disabled = false;
  }

  private getPercentage(): number {
    return ((this.value - this.min) / (this.max - this.min)) * 100;
  }

  private handleInput(e: Event) {
    if (this.disabled) return;

    const target = e.target as HTMLInputElement;
    const newValue = Number(target.value);
    this.value = newValue;

    this.dispatchEvent(
      new CustomEvent('slider-change', {
        detail: { value: newValue },
        bubbles: true,
        composed: true,
      })
    );
  }

  protected override render() {
    const percentage = this.getPercentage();
    const thumbPosition = `calc(${percentage}% - 8px)`;

    return html`
      <div class="container" data-slot="slider" ?data-disabled=${this.disabled}>
        <div class="track" data-slot="slider-track">
          <div class="range" data-slot="slider-range" style="width: ${percentage}%"></div>
        </div>
        <input
          type="range"
          min=${this.min}
          max=${this.max}
          step=${this.step}
          .value=${String(this.value)}
          ?disabled=${this.disabled}
          aria-valuemin=${this.min}
          aria-valuemax=${this.max}
          aria-valuenow=${this.value}
          @input=${this.handleInput}
        />
        <div class="thumb" data-slot="slider-thumb" style="left: ${thumbPosition}"></div>
      </div>
    `;
  }
}

customElements.define('graph-slider', GraphSlider);

declare global {
  interface HTMLElementTagNameMap {
    'graph-slider': GraphSlider;
  }
}
