// src/components/sidebar/StatsCard.tsx
/**
 * Reusable stats card component
 * Used across all right sidebar panels for consistent metric display
 */

interface StatsCardProps {
  label: string;
  value: string | number;
  highlighted?: boolean;
}

export function StatsCard({ 
  label, 
  value, 
  highlighted = false
}: StatsCardProps) {
  return (
    <div 
      className="flex-1 p-3 rounded-lg cursor-default"
      style={{
        backgroundColor: 'var(--color-card)',
        border: '1px solid var(--color-border)',
        transition: 'transform 0.15s ease-out, box-shadow 0.15s ease-out'
      }}
      onMouseEnter={(e) => {
        e.currentTarget.style.transform = 'scale(1.02)';
        e.currentTarget.style.boxShadow = '0 0 20px color-mix(in srgb, var(--primary) 15%, transparent)';
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.transform = 'scale(1)';
        e.currentTarget.style.boxShadow = 'none';
      }}
    >
      <div
        style={{
          fontFamily: 'Inter, sans-serif',
          fontSize: 'var(--text-small)',
          color: 'var(--color-muted-foreground)',
          marginBottom: 'var(--spacing-xs)'
        }}
      >
        {label}
      </div>
      <div
        style={{
          fontFamily: 'DM Sans, sans-serif',
          fontSize: 'var(--text-h3)',
          fontWeight: 'var(--font-weight-semibold)',
          color: highlighted ? 'rgba(168, 157, 255, 1)' : 'var(--color-foreground)'
        }}
      >
        {value}
      </div>
    </div>
  );
}

// src/components-lit/ui/stats-card.ts
/**
 * StatsCard Lit Component
 *
 * Reusable stats card component for displaying metrics.
 * Used across all right sidebar panels for consistent metric display.
 *
 * @example
 * ```html
 * <graph-stats-card label="Total" value="42"></graph-stats-card>
 * <graph-stats-card label="Selected" value="10" highlighted></graph-stats-card>
 * ```
 */

import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';

@customElement('graph-stats-card')
export class GraphStatsCard extends LitElement {
  // ========================================
  // Properties
  // ========================================

  /**
   * The label text displayed above the value
   */
  @property({ type: String, attribute: 'label' })
  declare label: string;

  /**
   * The value to display (can be string or number)
   */
  @property({ type: String, attribute: 'value' })
  declare value: string | number;

  /**
   * Whether to highlight the value with accent color
   */
  @property({ type: Boolean, attribute: 'highlighted' })
  declare highlighted: boolean;

  // ========================================
  // Styles
  // ========================================

  static styles = css`
    :host {
      display: block;
      flex: 1;
    }

    .container {
      padding: var(--spacing-md);
      border-radius: var(--radius-lg);
      background-color: var(--color-card);
      border: 1px solid var(--color-border);
      cursor: default;
      transition: transform 0.15s ease-out, box-shadow 0.15s ease-out;
    }

    .container:hover {
      transform: scale(1.02);
      box-shadow: 0 0 20px color-mix(in srgb, var(--primary) 15%, transparent);
    }

    .label {
      font-family: 'Inter', sans-serif;
      font-size: var(--text-small);
      color: var(--color-muted-foreground);
      margin-bottom: var(--spacing-xs);
    }

    .value {
      font-family: 'DM Sans', sans-serif;
      font-size: var(--text-h3);
      font-weight: var(--font-weight-semibold);
      color: var(--color-foreground);
    }

    .value.highlighted {
      color: rgba(168, 157, 255, 1);
    }
  `;

  // ========================================
  // Render
  // ========================================

  render() {
    return html`
      <div class="container">
        <div class="label">${this.label}</div>
        <div class="value ${this.highlighted ? 'highlighted' : ''}">
          ${this.value}
        </div>
      </div>
    `;
  }
}

// Export for TypeScript type checking
declare global {
  interface HTMLElementTagNameMap {
    'graph-stats-card': GraphStatsCard;
  }
}
