// src/components-lit/ui/metrics-section.ts
/**
 * MetricsSection Lit Component
 *
 * Displays node metrics using StatsCard components in a grid.
 *
 * @example
 * ```html
 * <graph-metrics-section
 *   dependencies-count="5"
 *   total-dependencies-count="10"
 * ></graph-metrics-section>
 * ```
 */

import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import './stats-card';

@customElement('graph-metrics-section')
export class GraphMetricsSection extends LitElement {
  // ========================================
  // Properties
  // ========================================

  @property({ type: Number, attribute: 'dependencies-count' })
  declare dependenciesCount: number;

  @property({ type: Number, attribute: 'dependents-count' })
  declare dependentsCount: number;

  @property({ type: Number, attribute: 'total-dependencies-count' })
  declare totalDependenciesCount: number;

  @property({ type: Number, attribute: 'total-dependents-count' })
  declare totalDependentsCount: number;

  @property({ type: Boolean, attribute: 'is-high-fan-in' })
  isHighFanIn: boolean = false;

  @property({ type: Boolean, attribute: 'is-high-fan-out' })
  isHighFanOut: boolean = false;

  // ========================================
  // Styles
  // ========================================

  static styles = css`
    :host {
      display: block;
      padding: var(--spacing-md) var(--spacing-md) var(--spacing-md);
      flex-shrink: 0;
    }

    .title {
      margin-bottom: 12px;
      font-family: 'Inter', sans-serif;
      font-size: var(--text-small);
      color: var(--color-muted-foreground);
    }

    .grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 12px;
    }
  `;

  // ========================================
  // Render
  // ========================================

  render() {
    return html`
      <div class="title">Metrics</div>

      <div class="grid">
        <graph-stats-card
          label="Dependencies Out"
          value="${this.dependenciesCount}/${this.totalDependenciesCount}"
        ></graph-stats-card>

        <graph-stats-card
          label="Dependencies In"
          value="${this.dependentsCount}/${this.totalDependentsCount}"
        ></graph-stats-card>
      </div>
    `;
  }
}

// Export for TypeScript type checking
declare global {
  interface HTMLElementTagNameMap {
    'graph-metrics-section': GraphMetricsSection;
  }
}

// src/components/nodeDetails/MetricsSection.tsx
/**
 * Node metrics section component
 */

import { StatsCard } from '../sidebar/StatsCard';
import { LitStatsCard } from '../../components-lit/wrappers/StatsCard';

interface MetricsSectionProps {
  dependenciesCount: number;
  dependentsCount: number;
  totalDependenciesCount: number;
  totalDependentsCount: number;
  isHighFanIn: boolean;
  isHighFanOut: boolean;
}

export function MetricsSection({
  dependenciesCount,
  dependentsCount,
  totalDependenciesCount,
  totalDependentsCount,
  isHighFanIn: _isHighFanIn,
  isHighFanOut: _isHighFanOut,
}: MetricsSectionProps) {
  return (
    <div className="px-4 pt-3 pb-4 shrink-0">
      {/* Section Title */}
      <div
        className="mb-3"
        style={{
          fontFamily: 'Inter, sans-serif',
          fontSize: 'var(--text-small)',
          color: 'var(--color-muted-foreground)',
        }}
      >
        Metrics
      </div>

      {/* Metrics Grid */}
      <div className="grid grid-cols-2 gap-3">
        <LitStatsCard
          label="Dependencies Out"
          value={`${dependenciesCount}/${totalDependenciesCount}`}
        />

        <LitStatsCard label="Dependencies In" value={`${dependentsCount}/${totalDependentsCount}`} />
      </div>
    </div>
  );
}
