// src/components-lit/ui/cluster-header.ts
/**
 * ClusterHeader Lit Component
 *
 * Header for cluster details panel with back button, icon, and cluster info.
 *
 * @example
 * ```html
 * <graph-cluster-header
 *   cluster-name="MyPackage"
 *   cluster-type="package"
 *   cluster-color="#8B5CF6"
 *   is-external
 * ></graph-cluster-header>
 * ```
 *
 * @fires back - Dispatched when back button is clicked
 */

import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { unsafeHTML } from 'lit/directives/unsafe-html.js';
import { icons } from '@/controllers/icon.adapter';

@customElement('graph-cluster-header')
export class GraphClusterHeader extends LitElement {
  // ========================================
  // Properties
  // ========================================

  @property({ type: String, attribute: 'cluster-name' })
  declare clusterName: string;

  @property({ type: String, attribute: 'cluster-type' })
  declare clusterType: 'package' | 'project';

  @property({ type: String, attribute: 'cluster-color' })
  declare clusterColor: string;

  @property({ type: Boolean, attribute: 'is-external' })
  declare isExternal: boolean;

  // ========================================
  // Styles
  // ========================================

  static styles = css`
    :host {
      display: block;
    }

    .container {
      display: flex;
      align-items: center;
      gap: 12px;
      padding: 12px var(--spacing-md);
      border-bottom: 1px solid var(--color-border);
    }

    .back-button {
      width: 24px;
      height: 24px;
      border-radius: var(--radius);
      display: flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
      background: none;
      border: none;
      color: var(--color-muted-foreground);
      cursor: pointer;
      transition: background-color 0.2s;
    }

    .back-button:hover {
      background-color: rgba(255, 255, 255, 0.05);
    }

    .back-button svg {
      width: 20px;
      height: 20px;
    }

    .content {
      display: flex;
      align-items: center;
      gap: 12px;
      flex: 1;
      min-width: 0;
    }

    .icon-box {
      width: 48px;
      height: 48px;
      border-radius: var(--radius-xl);
      display: flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
    }

    .icon-box svg {
      width: 24px;
      height: 24px;
    }

    .info {
      flex: 1;
      min-width: 0;
    }

    .name {
      font-family: 'DM Sans', sans-serif;
      font-size: var(--text-h3);
      font-weight: var(--font-weight-semibold);
      color: var(--color-foreground);
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }

    .origin {
      font-family: 'Inter', sans-serif;
      font-size: 13px;
      line-height: 18px;
      color: var(--color-muted-foreground);
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }
  `;

  // ========================================
  // Event Handlers
  // ========================================

  private handleBack() {
    this.dispatchEvent(
      new CustomEvent('back', {
        bubbles: true,
        composed: true,
      })
    );
  }

  // ========================================
  // Render
  // ========================================

  render() {
    const isPackage = this.clusterType === 'package';
    const clusterIcon = isPackage ? icons.Package : icons.Folder;
    const color = this.clusterColor || '#8B5CF6';

    return html`
      <div class="container">
        <!-- Back Button -->
        <button class="back-button" @click=${this.handleBack}>
          ${unsafeHTML(icons.ChevronLeft)}
        </button>

        <div class="content">
          <!-- Cluster Icon -->
          <div
            class="icon-box"
            style="
              background-color: ${color}15;
              box-shadow: 0 0 20px ${color}30, 0 0 40px ${color}15;
            "
          >
            <span style="color: ${color}">${unsafeHTML(clusterIcon)}</span>
          </div>

          <!-- Cluster Info -->
          <div class="info">
            <h2 class="name">${this.clusterName}</h2>
            <div class="origin">${this.isExternal ? 'External' : 'Internal'}</div>
          </div>
        </div>
      </div>
    `;
  }
}

// Export for TypeScript type checking
declare global {
  interface HTMLElementTagNameMap {
    'graph-cluster-header': GraphClusterHeader;
  }
}

// src/components/clusterDetails/ClusterHeader.tsx
/**
 * Cluster details header component
 * Shows cluster icon, name, and back button
 * All styling uses design system CSS variables
 */

import { ChevronLeft, Folder, Package } from 'lucide-react';

interface ClusterHeaderProps {
  clusterName: string;
  clusterType: 'package' | 'project';
  clusterColor: string;
  isExternal: boolean;
  onBack: () => void;
}

export function ClusterHeader({
  clusterName,
  clusterType,
  clusterColor,
  isExternal,
  onBack,
}: ClusterHeaderProps) {
  const isPackage = clusterType === 'package';
  const ClusterIcon = isPackage ? Package : Folder;

  return (
    <div
      className="flex items-center gap-3 px-4 py-3 border-b"
      style={{
        borderColor: 'var(--color-border)',
      }}
    >
      {/* Back Button */}
      <button
        onClick={onBack}
        className="size-6 rounded flex items-center justify-center shrink-0 hover:bg-white/5 transition-colors"
        style={{
          color: 'var(--color-muted-foreground)',
        }}
      >
        <ChevronLeft className="size-5" />
      </button>

      <div className="flex items-center gap-3 flex-1 min-w-0">
        {/* Icon - with glow effect matching node details */}
        <div
          className="size-12 rounded-xl flex items-center justify-center shrink-0"
          style={{
            backgroundColor: `${clusterColor}15`,
            boxShadow: `0 0 20px ${clusterColor}30, 0 0 40px ${clusterColor}15`,
          }}
        >
          <ClusterIcon className="size-6" strokeWidth={2} style={{ color: clusterColor }} />
        </div>

        {/* Cluster Name and Origin - vertical stack */}
        <div className="flex-1 min-w-0">
          <h2
            className="truncate"
            style={{
              fontFamily: 'DM Sans, sans-serif',
              fontSize: 'var(--text-h3)',
              fontWeight: 'var(--font-weight-semibold)',
              color: 'var(--color-foreground)',
            }}
          >
            {clusterName}
          </h2>

          {/* Origin subtitle */}
          <div
            className="truncate"
            style={{
              fontFamily: 'Inter, sans-serif',
              fontSize: '13px',
              lineHeight: '18px',
              color: 'var(--color-muted-foreground)',
            }}
          >
            {isExternal ? 'External' : 'Internal'}
          </div>
        </div>
      </div>
    </div>
  );
}
