// src/components-lit/ui/node-details-panel.ts
/**
 * NodeDetailsPanel Lit Component
 *
 * Full node details panel orchestrating all node detail components.
 * Uses utility function for dependency computation.
 *
 * @example
 * ```html
 * <graph-node-details-panel
 *   .node=${nodeData}
 *   .allNodes=${nodes}
 *   .edges=${edges}
 *   zoom="1.0"
 * ></graph-node-details-panel>
 * ```
 *
 * @fires close, node-select, cluster-select, node-hover, focus-node, show-dependents, show-impact
 */

import { LitElement, html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import type { GraphEdge, GraphNode } from '@/data/mockGraphData';
import type { Cluster } from '@/types/cluster';
import { computeNodeDependencies } from '@/utils/nodeUtils';
import './node-header';
import './node-info';
import './node-actions';
import './dependencies-list';
import './dependents-list';

@customElement('graph-node-details-panel')
export class GraphNodeDetailsPanel extends LitElement {
  // ========================================
  // Properties
  // ========================================

  @property({ attribute: false })
  declare node: GraphNode;

  @property({ attribute: false })
  declare allNodes: GraphNode[];

  @property({ attribute: false })
  declare edges: GraphEdge[];

  @property({ attribute: false })
  filteredEdges: GraphEdge[] | undefined;

  @property({ attribute: false })
  clusters: Cluster[] | undefined;

  @property({ type: String, attribute: 'view-mode' })
  viewMode: string = '';

  @property({ type: Number })
  declare zoom: number;

  // ========================================
  // Styles
  // ========================================

  static styles = css`
    :host {
      display: flex;
      flex-direction: column;
      height: 100%;
      overflow-y: auto;
    }
  `;

  // ========================================
  // Computed Values
  // ========================================

  private get nodeData() {
    return computeNodeDependencies(this.node, this.allNodes, this.edges, this.filteredEdges);
  }

  // ========================================
  // Event Handlers (bubble up)
  // ========================================

  private bubbleEvent(eventName: string, detail?: any) {
    this.dispatchEvent(
      new CustomEvent(eventName, {
        detail,
        bubbles: true,
        composed: true,
      })
    );
  }

  // ========================================
  // Render
  // ========================================

  render() {
    if (!this.node) return html``;

    const { dependencies, dependents, metrics } = this.nodeData;

    return html`
      <graph-node-header
        .node=${this.node}
        .zoom=${this.zoom}
        @close=${() => this.bubbleEvent('close')}
        @cluster-click=${(e: CustomEvent) => this.bubbleEvent('cluster-select', e.detail)}
      ></graph-node-header>

      <graph-metrics-section
        dependencies-count=${metrics.dependencyCount}
        dependents-count=${metrics.dependentCount}
        total-dependencies-count=${metrics.totalDependencyCount}
        total-dependents-count=${metrics.totalDependentCount}
      ></graph-metrics-section>

      <graph-node-actions
        .node=${this.node}
        view-mode=${this.viewMode}
        @focus-node=${(e: CustomEvent) => this.bubbleEvent('focus-node', e.detail)}
        @show-dependents=${(e: CustomEvent) => this.bubbleEvent('show-dependents', e.detail)}
        @show-impact=${(e: CustomEvent) => this.bubbleEvent('show-impact', e.detail)}
      ></graph-node-actions>

      <graph-dependencies-list
        .dependencies=${dependencies}
        @node-select=${(e: CustomEvent) => this.bubbleEvent('node-select', e.detail)}
        @node-hover=${(e: CustomEvent) => this.bubbleEvent('node-hover', e.detail)}
      ></graph-dependencies-list>

      <graph-dependents-list
        .dependents=${dependents}
        @node-select=${(e: CustomEvent) => this.bubbleEvent('node-select', e.detail)}
        @node-hover=${(e: CustomEvent) => this.bubbleEvent('node-hover', e.detail)}
      ></graph-dependents-list>

      <graph-node-info .node=${this.node}></graph-node-info>
    `;
  }
}

// Export for TypeScript type checking
declare global {
  interface HTMLElementTagNameMap {
    'graph-node-details-panel': GraphNodeDetailsPanel;
  }
}

// src/components-lit/wrappers/NodeDetailsPanel.tsx
/**
 * React Wrapper for GraphNodeDetailsPanel Lit Component
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { GraphNodeDetailsPanel } from '../ui/node-details-panel';
import type { GraphNode, GraphEdge } from '@/data/mockGraphData';
import type { Cluster } from '@/types/cluster';

export const LitNodeDetailsPanelElement = createComponent({
  tagName: 'graph-node-details-panel',
  elementClass: GraphNodeDetailsPanel,
  react: React,
  events: {
    onClose: 'close',
    onNodeSelect: 'node-select',
    onClusterSelect: 'cluster-select',
    onNodeHover: 'node-hover',
    onFocusNode: 'focus-node',
    onShowDependents: 'show-dependents',
    onShowImpact: 'show-impact',
  },
});

export interface LitNodeDetailsPanelProps extends React.HTMLAttributes<HTMLElement> {
  node?: GraphNode;
  allNodes?: GraphNode[];
  edges?: GraphEdge[];
  filteredEdges?: GraphEdge[];
  clusters?: Cluster[];
  viewMode?: string;
  zoom?: number;
  onClose?: (event: CustomEvent) => void;
  onNodeSelect?: (event: CustomEvent<{ node: GraphNode }>) => void;
  onClusterSelect?: (event: CustomEvent<{ clusterId: string }>) => void;
  onNodeHover?: (event: CustomEvent<{ nodeId: string | null }>) => void;
  onFocusNode?: (event: CustomEvent) => void;
  onShowDependents?: (event: CustomEvent) => void;
  onShowImpact?: (event: CustomEvent) => void;
}

export function NodeDetailsPanel({
  node,
  allNodes,
  edges,
  filteredEdges,
  clusters,
  viewMode = '',
  zoom = 1.0,
  onClose,
  onNodeSelect,
  onClusterSelect,
  onNodeHover,
  onFocusNode,
  onShowDependents,
  onShowImpact,
  ...props
}: LitNodeDetailsPanelProps = {}) {
  return (
    <LitNodeDetailsPanelElement
      node={node}
      allNodes={allNodes}
      edges={edges}
      filteredEdges={filteredEdges}
      clusters={clusters}
      view-mode={viewMode}
      zoom={zoom}
      onClose={onClose}
      onNodeSelect={onNodeSelect}
      onClusterSelect={onClusterSelect}
      onNodeHover={onNodeHover}
      onFocusNode={onFocusNode}
      onShowDependents={onShowDependents}
      onShowImpact={onShowImpact}
      {...props}
    />
  );
}
