// src/components-lit/ui/badge.ts
import { LitElement, html, css } from 'lit';

export type BadgeVariant = 'default' | 'secondary' | 'destructive' | 'outline';

/**
 * Graph Badge - A Lit Web Component for displaying badges
 *
 * Uses Shadow DOM for proper slot support and CSS custom properties for styling.
 *
 * @example
 * ```html
 * <graph-badge variant="default">New</graph-badge>
 * <graph-badge variant="secondary">Beta</graph-badge>
 * <graph-badge variant="destructive">Error</graph-badge>
 * <graph-badge variant="outline">Info</graph-badge>
 * ```
 */
export class GraphBadge extends LitElement {
  static override properties = {
    variant: { type: String, reflect: true },
  };

  static override styles = css`
    :host {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      border-radius: var(--radii-md);
      border: 1px solid transparent;
      padding-inline: var(--spacing-2);
      padding-block: 2px;
      font-size: var(--font-sizes-xs);
      font-weight: var(--font-weights-medium);
      width: fit-content;
      white-space: nowrap;
      flex-shrink: 0;
      gap: var(--spacing-1);
      transition: colors var(--durations-normal);
      overflow: hidden;
    }

    /* Default variant */
    :host([variant='default']),
    :host(:not([variant])) {
      background-color: var(--colors-primary);
      color: var(--colors-primary-foreground);
    }

    /* Secondary variant */
    :host([variant='secondary']) {
      background-color: var(--colors-secondary);
      color: var(--colors-secondary-foreground);
    }

    /* Destructive variant */
    :host([variant='destructive']) {
      background-color: var(--colors-destructive);
      color: var(--colors-white);
    }

    /* Outline variant */
    :host([variant='outline']) {
      background-color: transparent;
      border-color: var(--colors-border);
      color: var(--colors-foreground);
    }

    ::slotted(svg) {
      width: 12px;
      height: 12px;
      pointer-events: none;
    }
  `;

  declare variant: BadgeVariant;

  constructor() {
    super();
    this.variant = 'default';
  }

  protected override render() {
    return html`<slot></slot>`;
  }
}

// Register the custom element
customElements.define('graph-badge', GraphBadge);

// Type declaration for HTML element registry
declare global {
  interface HTMLElementTagNameMap {
    'graph-badge': GraphBadge;
  }
}

// src/components/ui/badge.tsx
import { cva, type VariantProps } from 'class-variance-authority@0.7.1';
import { Slot } from '@radix-ui/react-slot@1.1.2';
import type * as React from 'react';

import { cn } from './utils';

const badgeVariants = cva(
  'inline-flex items-center justify-center rounded-md border px-2 py-0.5 text-xs font-medium w-fit whitespace-nowrap shrink-0 [&>svg]:size-3 gap-1 [&>svg]:pointer-events-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive transition-[color,box-shadow] overflow-hidden',
  {
    variants: {
      variant: {
        default: 'border-transparent bg-primary text-primary-foreground [a&]:hover:bg-primary/90',
        secondary:
          'border-transparent bg-secondary text-secondary-foreground [a&]:hover:bg-secondary/90',
        destructive:
          'border-transparent bg-destructive text-white [a&]:hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60',
        outline: 'text-foreground [a&]:hover:bg-accent [a&]:hover:text-accent-foreground',
      },
    },
    defaultVariants: {
      variant: 'default',
    },
  },
);

function Badge({
  className,
  variant,
  asChild = false,
  ...props
}: React.ComponentProps<'span'> & VariantProps<typeof badgeVariants> & { asChild?: boolean }) {
  const Comp = asChild ? Slot : 'span';

  return (
    <Comp data-slot="badge" className={cn(badgeVariants({ variant }), className)} {...props} />
  );
}

export { Badge, badgeVariants };
